// lib/utils/ucf_majors.dart

const List<String> ucfMajors = [
  'Accounting',
  'Aerospace Engineering',
  'African American Studies',
  'Agricultural Economics',
  'Anthropology',
  'Applied Mathematics',
  'Architecture',
  'Art History',
  'Biochemistry',
  'Biology',
  'Biomedical Engineering',
  'Business Administration',
  'Chemical Engineering',
  'Chemistry',
  'Civil Engineering',
  'Communication Sciences and Disorders',
  'Computer Engineering',
  'Computer Science',
  'Construction Engineering',
  'Criminal Justice',
  'Cybersecurity',
  'Data Analytics',
  'Digital Media',
  'Early Childhood Education',
  'Economics',
  'Electrical Engineering',
  'Elementary Education',
  'Emergency Management',
  'Engineering Technology',
  'English',
  'Environmental Engineering',
  'Environmental Studies',
  'Finance',
  'Forensic Science',
  'Game Design',
  'General Business',
  'Geography',
  'Health Sciences',
  'History',
  'Hospitality Management',
  'Human Communication',
  'Industrial Engineering',
  'Information Technology',
  'Interdisciplinary Studies',
  'International and Global Studies',
  'Journalism',
  'Kinesiology',
  'Latin American Studies',
  'Legal Studies',
  'Liberal Studies',
  'Management',
  'Management Information Systems',
  'Marketing',
  'Mathematics',
  'Mechanical Engineering',
  'Medical Laboratory Sciences',
  'Microbiology',
  'Music',
  'Nursing',
  'Nutrition and Dietetics',
  'Philosophy',
  'Photography',
  'Physics',
  'Political Science',
  'Psychology',
  'Public Administration',
  'Public Health',
  'Real Estate',
  'Religious Studies',
  'Social Work',
  'Sociology',
  'Software Engineering',
  'Statistics',
  'Studio Art',
  'Supply Chain Management',
  'Theatre',
  'Urban and Regional Planning',
  'Women\'s and Gender Studies',
  'Writing and Rhetoric',
];
